export default function api() {
  const url = process.env.REACT_APP_PROD_URL;

  return {
    register: `${url}api/auth/register/`,
    "send-code": `${url}api/auth/send-code/`,
    "verify-code": `${url}api/auth/verify-code/`,
    refresh: `${url}api/auth/refresh/`,
    create: `${url}api/manager/create/`,
    salon: `${url}api/salon/`,
    "salon-barber": `${url}api/salon-barber/`,
    barber: `${url}api/barber/`,
    category: `${url}api/category/`,
    "barber-service": `${url}api/barber-service/`,
    reservation: `${url}api/order/`,
    user: `${url}api/user/`,
    "forget-pass": `${url}api/forget-pass/`,
    "social-network": `${url}api/social-network/`,
    "salon-social-media": `${url}api/salon-social-media/`,
    "best-salons": `${url}api/best/salon/`,
    "best-barbers": `${url}api/best/barber/`,
    order: `${url}api/order/`,
    "cancel-order": `${url}api/order-action/cancel/`,
    "payment-order": `${url}api/order-action/payment/`,
    "reserve-order": `${url}api/order-action/reserve/`,
    "ticket-category": `${url}api/ticket-category/`,
    ticket: `${url}api/ticket/`,
    "barber-category-gallery": `${url}api/barber-category-gallery/`,
    comment: `${url}api/order-comment/`,
    wallet: `${url}api/wallet/`,
    "wallet-card": `${url}api/wallet-card/`,
    "add-wallet-card": `${url}api/wallet-card-action/add/`,
    withdrawal: `${url}api/withdrawal/`,
  };
}
